# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0002_activity_detailed_vectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effort',
            name='diff_last_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='effort',
            name='diff_last_speed_s',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
