# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0005_auto_20171107_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
