# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-07 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0007_auto_20180207_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerSpotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_code', models.CharField(blank=True, max_length=100, null=True)),
                ('spotify_token', models.CharField(blank=True, max_length=100, null=True)),
                ('spotify_refresh_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='poweruser',
            name='listener_spotify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='powersong.ListenerSpotify'),
        ),
    ]
