# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-09 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0008_auto_20181107_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poweruser',
            name='listener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='powersong.Listener'),
        ),
    ]
