# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-11 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0009_auto_20181109_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='powersong.Song'),
        ),
    ]
