# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-11 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0010_song_original_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongEffortPerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField(blank=True, null=True)),
                ('count', models.BinaryField(blank=True, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powersong.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powersong.PowerUser')),
            ],
        ),
        migrations.AddField(
            model_name='effort',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
