# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-11 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0011_auto_20181111_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='effort',
            name='time',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
