# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-15 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0013_auto_20181115_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
