# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-17 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0014_auto_20181115_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='flagged_hr',
            field=models.BooleanField(default=False),
        ),
    ]
