# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0016_auto_20181118_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerspotify',
            name='nickname',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenerspotify',
            name='product',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listenerspotify',
            name='profile_image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='listenerspotify',
            name='real_name',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenerspotify',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='workout_type',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
