# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0017_auto_20181126_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenerspotify',
            name='real_name',
            field=models.CharField(max_length=30),
        ),
    ]
