# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0018_auto_20181126_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='last_celery_task_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
