# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-18 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0019_athlete_last_celery_task_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
