# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-19 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0020_auto_20190218_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='strava_edit_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
