# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-19 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0021_athlete_strava_edit_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='share_activity_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athlete',
            name='share_activity_songs',
            field=models.BooleanField(default=False),
        ),
    ]
