# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0023_auto_20191022_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='strava_edit_token',
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
