# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-06 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0024_auto_20191105_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='share_activity_songs_mode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
