# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-04 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0025_athlete_share_activity_songs_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='acousticness',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='song',
            name='danceability',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='song',
            name='instrumentalness',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='song',
            name='key',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='song',
            name='liveness',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='song',
            name='loudness',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='song',
            name='mode',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='song',
            name='speechiness',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='song',
            name='time_signature',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='song',
            name='valence',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='share_activity_songs_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Simple'), (1, 'Time'), (2, 'Distance'), (3, 'Time + Distance')], default=0),
        ),
    ]
