# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powersong', '0027_auto_20210405_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteSongCadence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.FloatField()),
                ('listen_count', models.IntegerField()),
                ('act_type', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='poweruser',
            name='join_date',
            field=models.DateTimeField(auto_now=True, null=True, default=None),
        ),
        migrations.AddField(
            model_name='athletesongcadence',
            name='poweruser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='powersong.PowerUser'),
        ),
        migrations.AddField(
            model_name='athletesongcadence',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='powersong.Song'),
        ),
    ]
