# Generated by Django 4.1 on 2022-08-18 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("powersong", "0028_auto_20220809_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="flagged",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="activity",
            name="flagged_hr",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="effort",
            name="flagged",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="effort",
            name="flagged_hr",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="poweruser",
            name="athlete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="powersong.athlete",
            ),
        ),
        migrations.AlterField(
            model_name="poweruser",
            name="join_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="original_song",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="powersong.song",
            ),
        ),
    ]
